### ISSUE TITLE
Option for "BreakAlways" that implies breakage of containing "BreakIfNeeded"

### ISSUE THREAD

**Issue by jordwalke** [mjambon/easy-format#5]
Currently, if you configure the inner list to always break, the outer list will perform as follows:

    <breakMeIfNeeded><alwaysBreak>
                        a
                        b
                        c
                      </alwaysBreak><breakMeIfNeeded>

For formatting source code, you sometimes want to say things like "switch statements should always break", and that should imply that everything around it should break if it is reasonable to do so:

It would be awesome to have a setting that achieves the following instead of the previous output:

    <breakMeIfNeeded>
      <alwaysBreak>
        a
        b
        c
      </alwaysBreak>
    <breakMeIfNeeded>

**Comment by mjambon** [comment]
I just implemented that by rewriting the tree just before printing it, which turns the style of wrappable lists into lists with forced breaks if any of their descendants/sublists has the style `Force_breaks_rec`.

The example below is taken from `simple_example.out` produced by `make test`. The pluses represent the width of the printing area.
```
*** wrappable outer list, inner list using `Force_breaks ***
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[ 0, [
       1.23456,
       9.87654
     ], 1, 2, 3 ]
++++++++++++++++++++
[
  0,
  [
    1.23456,
    9.87654
  ], 1, 2, 3
]

*** wrappable outer list, inner list using `Force_breaks_rec ***
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[
  0,
  [
    1.23456,
    9.87654
  ],
  1,
  2,
  3
]
++++++++++++++++++++
[
  0,
  [
    1.23456,
    9.87654
  ],
  1,
  2,
  3
]
```

**Comment by jordwalke** [comment]
This looks excellent! Can't wait to try it.

**Comment by jordwalke** [comment]
I tried this out and it looks like there might be one tweak necessary - maybe I can get your thoughts on it.
It seems that this behavior should apply when a containing list is `Never_wrap`, but currently it only applies when the containing list is `Always_wrap`. It sounds weird at first, to say `Never_wrap` should sometimes wrap, but the way I understood it, was that `Never_wrap` actually means "wrap only if needed". That is consistent with the [document](http://mjambon.com/easy-format.html) and with what I've seen happen in practice. Thoughts on tweaking the behavior so that the same applies to `Never_wrap` containers? I could probably send the PR if it's as easy as it sounds.
