### ISSUE TITLE
Support for MSVC

### ISSUE THREAD

**Issue by modlfo** [mjambon/easy-format#7]
I'm building easy-format on windows with the MSVC port of ocaml. The library builds correctly but on install it is looking for a ".o" file. Some time ago I forked it and made the following changes to install it:

https://github.com/modlfo/easy-format/commit/145d4fdae98ed566b2165ab854aa885bc009cc6a

Do you have any way of detecting that is being compiled with MSVC so the makefile can be fixed for all platforms?

**Comment by mjambon** [comment]
The simplest way might be to install whatever files were by the compiler and ignore missing files.

Another way would be to use a tool like oasis, which for various reasons I don't really like.

**Comment by modlfo** [comment]
I was taking a look at ocamlfind and seems that there's an argument to "install" called "-optional". If I pass the .o and .obj  it ignores the files that were not found.

Here is the change I made:

https://github.com/modlfo/easy-format/commit/e255a5e3439dd7a02816fc35e0182c54ddada4f1

I'm not sure if it's a good idea using the -optional argument.

**Comment by oandrieu** [comment]
Other options
- use this in the Makefile:
`include $(shell ocamlfind ocamlopt -where)/Makefile.config`
and use `.$(O)` instead of `.o` in the rest of the Makfile

- use `easy_format.o*` in `NC_INSTALL_FILES`

**Comment by mjambon** [comment]
We've switched the build system to jbuilder/dune, which should take care of platform-specific issues.
